[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Telethon-MCUB"
dynamic = ["version"]
description = "Full-featured Telegram client library for Python 3, forked for userbot use"
readme = "README.rst"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Lonami Exo", email = "totufals@hotmail.com" }
]
requires-python = ">=3.9"
keywords = ["telegram", "api", "chat", "client", "library", "messaging", "mtproto", "userbot"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Communications :: Chat",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = ["pyaes", "rsa"]

[project.optional-dependencies]
cryptg = ["cryptg"]
socks = ["python-socks[asyncio]"]
media = ["hachoir", "pillow"]
speedups = ["isal"]
all = [
    "cryptg",
    "python-socks[asyncio]",
    "hachoir",
    "pillow",
    "isal",
]

[project.urls]
Homepage = "https://github.com/hairpin01/Telethon-MCUB"
Repository = "https://github.com/hairpin01/Telethon-MCUB"
Issues = "https://github.com/hairpin01/Telethon-MCUB/issues"

[tool.setuptools.dynamic]
version = { attr = "telethon.version.__version__" }

[tool.setuptools.packages.find]
include = ["telethon*"]
exclude = ["telethon_*", "tests*", "build*", "dist*", "*.egg-info*", "deps*"]
namespaces = false
